-- =====================================================
-- Dungeon Stage System Migration Fix Script
-- =====================================================
-- 이 스크립트는 migration.sql이 이미 실행된 것으로 기록되어
-- 실제 테이블은 생성되지 않은 문제를 수정합니다.
-- =====================================================

BEGIN;

-- 1. 기존 Migration 기록 삭제 (테이블이 실제로 없으므로)
DELETE FROM "__EFMigrationsHistory"
WHERE "MigrationId" = '20251018112141_AddDungeonStageSystem';

-- 2. BattleLogs에 DungeonStageId 컬럼 추가 (이미 있으면 에러 무시)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'BattleLogs' AND column_name = 'DungeonStageId'
    ) THEN
        ALTER TABLE "BattleLogs" ADD "DungeonStageId" integer;
    END IF;
END $$;

-- 3. CharacterDungeonProgresses 테이블 생성
CREATE TABLE IF NOT EXISTS "CharacterDungeonProgresses" (
    "Id" uuid NOT NULL,
    "CharacterId" uuid NOT NULL,
    "HighestStageClearedNormal" integer NOT NULL DEFAULT 0,
    "HighestStageClearedHard" integer NOT NULL DEFAULT 0,
    "HighestStageClearedNightmare" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CharacterDungeonProgresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CharacterDungeonProgresses_Characters_CharacterId"
        FOREIGN KEY ("CharacterId") REFERENCES "Characters" ("Id") ON DELETE CASCADE
);

-- 4. DungeonStages 테이블 생성
CREATE TABLE IF NOT EXISTS "DungeonStages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "RequiredLevel" integer NOT NULL,
    "MonsterId" uuid NOT NULL,
    "BaseExperience" integer NOT NULL,
    "BaseGold" integer NOT NULL,
    "FirstClearBonusExp" integer,
    "FirstClearBonusGold" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DungeonStages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DungeonStages_Monsters_MonsterId"
        FOREIGN KEY ("MonsterId") REFERENCES "Monsters" ("Id") ON DELETE RESTRICT
);

-- 5. 인덱스 생성 (이미 있으면 무시)
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CharacterDungeonProgresses_CharacterId_Unique"
    ON "CharacterDungeonProgresses" ("CharacterId");

CREATE INDEX IF NOT EXISTS "IX_DungeonStages_MonsterId"
    ON "DungeonStages" ("MonsterId");

CREATE INDEX IF NOT EXISTS "IX_DungeonStages_RequiredLevel"
    ON "DungeonStages" ("RequiredLevel");

-- 6. Migration 기록 추가
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251018112141_AddDungeonStageSystem', '9.0.9');

COMMIT;

-- 7. 생성 결과 확인
SELECT
    'CharacterDungeonProgresses' as table_name,
    COUNT(*) as row_count
FROM "CharacterDungeonProgresses"
UNION ALL
SELECT
    'DungeonStages' as table_name,
    COUNT(*) as row_count
FROM "DungeonStages";

-- 8. Migration 기록 확인
SELECT "MigrationId", "ProductVersion"
FROM "__EFMigrationsHistory"
WHERE "MigrationId" = '20251018112141_AddDungeonStageSystem';
