using IdleRPG.Application.DTOs.Rewards;
using IdleRPG.Application.Interfaces;
using Microsoft.Extensions.Logging;
using System.Security.Cryptography;

namespace IdleRPG.Application.Services
{
    /// <summary>
    /// Drop System의 Orchestrator 구현
    ///
    /// [학습 포인트 1] Dependency Injection (의존성 주입)
    /// - ILootTableCache: 캐시 전략 추상화 (현재: IMemoryCache, 미래: Redis)
    /// - IDropCalculator: 확률 계산 로직 추상화
    /// - 생성자로 주입받아 느슨한 결합 유지
    ///
    /// [학습 포인트 2] Seed 자동 생성 전략
    /// - Environment.TickCount: 프로그램 시작 후 경과 시간 (ms)
    /// - Guid.NewGuid(): 고유 식별자 (128bit 랜덤)
    /// - XOR 연산: 두 값을 섞어서 더 랜덤하게
    ///
    /// [학습 포인트 3] 방어적 프로그래밍 (Defensive Programming)
    /// - LootTable이 null이어도 예외 던지지 않고 빈 리스트 반환
    /// - 게임 서버는 크래시보다 부분 실패가 낫다
    /// - 대신 로그를 명확히 남겨 디버깅 가능하게
    ///
    /// [학습 포인트 4] 확장 포인트
    /// - TODO(human): VIP 보너스, 이벤트 배율 등 비즈니스 규칙 추가 가능
    /// - Calculator는 순수 로직만, Service에서 규칙 적용
    /// </summary>
    public class DropService : IDropService
    {
        private readonly ILootTableCache _lootTableCache;
        private readonly IDropCalculator _dropCalculator;
        private readonly ILogger<DropService> _logger;

        public DropService(
            ILootTableCache lootTableCache,
            IDropCalculator dropCalculator,
            ILogger<DropService> logger)
        {
            _lootTableCache = lootTableCache;
            _dropCalculator = dropCalculator;
            _logger = logger;
        }

        public async Task<List<RewardDto>> RollLootTableAsync(
            int lootTableId,
            int? seed = null,
            bool allowDuplicates = false)
        {
            _logger.LogInformation(
                "Rolling LootTable {LootTableId} with seed {Seed}, allowDuplicates: {AllowDuplicates}",
                lootTableId, seed, allowDuplicates);

            // 1단계: LootTable 조회 (캐시 우선, Cache-Aside Pattern)
            var lootTable = await _lootTableCache.GetAsync(lootTableId);

            if (lootTable == null)
            {
                _logger.LogWarning("LootTable {LootTableId} not found. Returning empty rewards.", lootTableId);
                return new List<RewardDto>();  // 빈 리스트 반환 (예외 던지지 않음)
            }

            // 2단계: Seed 생성 (null이면 자동 생성)
            int actualSeed = seed ?? GenerateRandomSeed();

            _logger.LogDebug(
                "Using seed {Seed} for LootTable {LootTableId} (auto-generated: {IsAutoGenerated})",
                actualSeed, lootTableId, seed == null);

            // 3단계: 확률 계산 (순수 로직, 외부 의존성 없음)
            var rewards = _dropCalculator.CalculateRewards(lootTable, actualSeed, allowDuplicates);

            _logger.LogInformation(
                "LootTable {LootTableId} rolled successfully. Rewards: {Count} items (Seed: {Seed})",
                lootTableId, rewards.Count, actualSeed);

            // 4단계: 비즈니스 규칙 적용 (미래 확장 포인트)
            // TODO(human): VIP 보너스, 이벤트 배율 등 적용
            // 예: rewards = ApplyVipBonus(rewards, userId);
            // 예: rewards = ApplyEventMultiplier(rewards, eventId);(rewards, eventId);

            return rewards;
        }

        public async Task InvalidateCacheAsync(int lootTableId)
        {
            _logger.LogInformation("Invalidating cache for LootTable {LootTableId}", lootTableId);
            await _lootTableCache.RemoveAsync(lootTableId);
        }

        public async Task InvalidateAllCachesAsync()
        {
            _logger.LogInformation("Invalidating all LootTable caches");
            await _lootTableCache.RemoveAllAsync();
        }

        /// <summary>
        /// 진짜 랜덤 Seed 생성 (개선 버전)
        ///
        /// [학습 포인트 1] RandomNumberGenerator란?
        /// - .NET의 암호학적으로 안전한 난수 생성기 (CSPRNG)
        /// - OS 레벨 엔트로피 소스 활용 (Windows: CryptGenRandom, Linux: /dev/urandom)
        /// - 예측 불가능한 고품질 난수 생성
        ///
        /// [학습 포인트 2] 기존 방식 (TickCount ^ Guid) vs 개선 방식
        ///
        /// 기존:
        /// - Environment.TickCount: 프로그램 시작 후 경과 시간 (ms)
        /// - Guid.NewGuid().GetHashCode(): 128bit → 32bit 해시 (충돌 가능)
        /// - XOR 조합: 복잡하지만 엔트로피 품질 일정하지 않음
        ///
        /// 개선:
        /// - RandomNumberGenerator.GetInt32(): OS 엔트로피 직접 활용
        /// - 암호학적 강도 (게임에선 과도하지만 품질 보장)
        /// - 코드 단순화 (한 줄, 의도 명확)
        ///
        /// [학습 포인트 3] 성능 고려사항
        /// - RandomNumberGenerator는 System.Random보다 약 10배 느림
        /// - 하지만 Seed 생성은 던전 클리어당 1회만 (병목 아님)
        /// - 확률 계산(SelectItemByWeight)은 System.Random 사용 (빠름)
        ///
        /// [학습 포인트 4] 언제 CSPRNG를 사용해야 하는가?
        /// - 보안 관련: JWT 토큰, 세션 ID, 비밀번호 솔트 → 필수
        /// - 게임 로직: 가챠, 드랍, 크리티컬 → 선택적 (품질 향상)
        /// - 성능 민감: 전투 히트 판정 (초당 100회+) → System.Random 사용
        /// </summary>
        private static int GenerateRandomSeed()
        {
            // OS 엔트로피 기반 고품질 난수 생성
            // int 전체 범위에서 균등 분포 보장
            return RandomNumberGenerator.GetInt32(int.MinValue, int.MaxValue);
        }
    }
}
