using IdleRPG.Application.DTOs.Rewards;
using IdleRPG.Application.Interfaces;
using Microsoft.Extensions.Logging;

namespace IdleRPG.Application.Services
{
    /// <summary>
    /// Drop System의 Orchestrator 구현
    ///
    /// [학습 포인트 1] Dependency Injection (의존성 주입)
    /// - ILootTableCache: 캐시 전략 추상화 (현재: IMemoryCache, 미래: Redis)
    /// - IDropCalculator: 확률 계산 로직 추상화
    /// - 생성자로 주입받아 느슨한 결합 유지
    ///
    /// [학습 포인트 2] Seed 자동 생성 전략
    /// - Environment.TickCount: 프로그램 시작 후 경과 시간 (ms)
    /// - Guid.NewGuid(): 고유 식별자 (128bit 랜덤)
    /// - XOR 연산: 두 값을 섞어서 더 랜덤하게
    ///
    /// [학습 포인트 3] 방어적 프로그래밍 (Defensive Programming)
    /// - LootTable이 null이어도 예외 던지지 않고 빈 리스트 반환
    /// - 게임 서버는 크래시보다 부분 실패가 낫다
    /// - 대신 로그를 명확히 남겨 디버깅 가능하게
    ///
    /// [학습 포인트 4] 확장 포인트
    /// - TODO(human): VIP 보너스, 이벤트 배율 등 비즈니스 규칙 추가 가능
    /// - Calculator는 순수 로직만, Service에서 규칙 적용
    /// </summary>
    public class DropService : IDropService
    {
        private readonly ILootTableCache _lootTableCache;
        private readonly IDropCalculator _dropCalculator;
        private readonly ILogger<DropService> _logger;

        public DropService(
            ILootTableCache lootTableCache,
            IDropCalculator dropCalculator,
            ILogger<DropService> logger)
        {
            _lootTableCache = lootTableCache;
            _dropCalculator = dropCalculator;
            _logger = logger;
        }

        public async Task<List<RewardDto>> RollLootTableAsync(
            int lootTableId,
            int? seed = null,
            bool allowDuplicates = false)
        {
            _logger.LogInformation(
                "Rolling LootTable {LootTableId} with seed {Seed}, allowDuplicates: {AllowDuplicates}",
                lootTableId, seed, allowDuplicates);

            // Step 1: LootTable 조회 (캐시 우선, Cache-Aside Pattern)
            var lootTable = await _lootTableCache.GetAsync(lootTableId);

            if (lootTable == null)
            {
                _logger.LogWarning("LootTable {LootTableId} not found. Returning empty rewards.", lootTableId);
                return new List<RewardDto>();  // 빈 리스트 반환 (예외 던지지 않음)
            }

            // Step 2: Seed 생성 (null이면 자동 생성)
            int actualSeed = seed ?? GenerateRandomSeed();

            _logger.LogDebug(
                "Using seed {Seed} for LootTable {LootTableId} (auto-generated: {IsAutoGenerated})",
                actualSeed, lootTableId, seed == null);

            // Step 3: 확률 계산 (순수 로직, 외부 의존성 없음)
            var rewards = _dropCalculator.CalculateRewards(lootTable, actualSeed, allowDuplicates);

            _logger.LogInformation(
                "LootTable {LootTableId} rolled successfully. Rewards: {Count} items (Seed: {Seed})",
                lootTableId, rewards.Count, actualSeed);

            // Step 4: 비즈니스 규칙 적용 (미래 확장 포인트)
            // TODO(human): VIP 보너스, 이벤트 배율 등 적용
            // 예: rewards = ApplyVipBonus(rewards, userId);
            // 예: rewards = ApplyEventMultiplier(rewards, eventId);

            return rewards;
        }

        public async Task InvalidateCacheAsync(int lootTableId)
        {
            _logger.LogInformation("Invalidating cache for LootTable {LootTableId}", lootTableId);
            await _lootTableCache.RemoveAsync(lootTableId);
        }

        public async Task InvalidateAllCachesAsync()
        {
            _logger.LogInformation("Invalidating all LootTable caches");
            await _lootTableCache.RemoveAllAsync();
        }

        /// <summary>
        /// 진짜 랜덤 Seed 생성
        ///
        /// [학습 포인트] 왜 XOR 연산을 사용하는가?
        ///
        /// Environment.TickCount만 사용:
        /// - 문제: 같은 시간에 호출되면 동일한 Seed
        /// - 예: 두 던전이 동시에 클리어되면 같은 보상
        ///
        /// Guid.NewGuid().GetHashCode()만 사용:
        /// - 문제: GetHashCode()는 32bit, 충돌 가능성
        ///
        /// XOR 조합:
        /// - TickCount의 시간 기반 랜덤성 + Guid의 고유성
        /// - 충돌 확률 극도로 낮음
        /// - 게임 서버에서 널리 사용되는 패턴
        /// </summary>
        private static int GenerateRandomSeed()
        {
            // XOR: 두 값의 비트를 섞어서 더 랜덤하게
            // 예: 1010 XOR 0110 = 1100
            return Environment.TickCount ^ Guid.NewGuid().GetHashCode();
        }
    }
}
