// <auto-generated />
using System;
using IdleRPG.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdleRPG.Infrastructure.Migrations
{
    [DbContext(typeof(GameDBContext))]
    [Migration("20251125024430_AddQuestEntity")]
    partial class AddQuestEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdleRPG.Domain.Entities.BattleLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BattleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("integer");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("integer");

                    b.Property<int?>("DungeonStageId")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceGained")
                        .HasColumnType("integer");

                    b.Property<int>("GoldGained")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVictory")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId")
                        .HasDatabaseName("IX_BattleLogs_MonsterId");

                    b.HasIndex("CharacterId", "BattleDate")
                        .HasDatabaseName("IX_BattleLogs_CharacterId_BattleDate");

                    b.ToTable("BattleLogs", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Crystal")
                        .HasColumnType("bigint");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("GachaPityCount")
                        .HasColumnType("integer");

                    b.Property<long>("Gold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("LastLoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("PetGachaCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.CharacterBattleProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HighestStageClearedHard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("HighestStageClearedNightmare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("HighestStageClearedNormal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("IX_CharacterBattleProgresses_CharacterId_Unique");

                    b.ToTable("CharacterBattleProgresses", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.CharacterSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<int>("SkillTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillTemplateId");

                    b.HasIndex("CharacterId", "SkillTemplateId")
                        .IsUnique();

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("RoomId", "CreatedAt")
                        .HasDatabaseName("IX_ChatMessages_RoomId_CreatedAt");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("IX_ChatRooms_GuildId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_ChatRooms_Type");

                    b.ToTable("ChatRooms", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.ChatRoomParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("IX_ChatRoomParticipants_CharacterId");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("IX_ChatRoomParticipants_RoomId");

                    b.HasIndex("RoomId", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("IX_ChatRoomParticipants_RoomId_CharacterId");

                    b.ToTable("ChatRoomParticipants", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonDifficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseExp")
                        .HasColumnType("integer");

                    b.Property<long>("BaseGold")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DailyEntryLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("EntryCostGold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("LootTableId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWaves")
                        .HasColumnType("integer");

                    b.Property<int>("RecommendedPower")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.HasIndex("TemplateId");

                    b.ToTable("DungeonDifficulties", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("DifficultyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("DifficultyId");

                    b.ToTable("DungeonProgresses", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonRunHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClearedWave")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("CharacterId", "CompletedAt");

                    b.ToTable("DungeonRunHistories", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseExperience")
                        .HasColumnType("integer");

                    b.Property<int>("BaseGold")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FirstClearBonusExp")
                        .HasColumnType("integer");

                    b.Property<int?>("FirstClearBonusGold")
                        .HasColumnType("integer");

                    b.Property<int?>("LootTableId")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.HasIndex("MonsterId");

                    b.HasIndex("RequiredLevel")
                        .HasDatabaseName("IX_DungeonStages_RequiredLevel");

                    b.ToTable("DungeonStages", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DungeonTemplates", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonWave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DifficultyId")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid");

                    b.Property<int>("WaveNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("MonsterId");

                    b.ToTable("DungeonWaves", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseAttack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("BaseDefense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("BaseHp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EnhancementLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Rarity");

                    b.HasIndex("CharacterId", "Slot");

                    b.ToTable("Equipments", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.EquippedPets", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EquippedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "SlotIndex");

                    b.HasIndex("PetId")
                        .IsUnique()
                        .HasDatabaseName("UK_EquippedPets_PetId");

                    b.ToTable("EquippedPets", null, t =>
                        {
                            t.HasCheckConstraint("CK_EquippedPets_SlotIndex", "\"SlotIndex\" >= 1 AND \"SlotIndex\" <= 3");
                        });
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.GachaHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SkillTemplateId")
                        .HasColumnType("integer");

                    b.Property<bool>("WasPity")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SkillTemplateId");

                    b.HasIndex("CharacterId", "CreatedAt")
                        .IsDescending();

                    b.ToTable("GachaHistories", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.ItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaxStackSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(999);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.LootItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentRarity")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipmentSlot")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGuaranteed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ItemTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("LootTableId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("MinQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("LootItems", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.LootTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumberOfRolls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("LootTables", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attack")
                        .HasColumnType("integer");

                    b.Property<float>("AttackSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<float>("CritDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1.5f);

                    b.Property<float>("CritRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.05f);

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<float>("Evasion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.05f);

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("integer");

                    b.Property<int>("GoldReward")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.ToTable("Monsters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Attack = 10,
                            AttackSpeed = 0.8f,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CritDamage = 1.3f,
                            CritRate = 0.03f,
                            Defense = 5,
                            Evasion = 0.02f,
                            ExperienceReward = 10,
                            GoldReward = 5,
                            Level = 1,
                            MaxHealth = 50,
                            Name = "슬라임",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Attack = 30,
                            AttackSpeed = 1f,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CritDamage = 1.5f,
                            CritRate = 0.05f,
                            Defense = 15,
                            Evasion = 0.05f,
                            ExperienceReward = 50,
                            GoldReward = 25,
                            Level = 5,
                            MaxHealth = 150,
                            Name = "고블린",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Attack = 60,
                            AttackSpeed = 0.7f,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CritDamage = 1.8f,
                            CritRate = 0.04f,
                            Defense = 30,
                            Evasion = 0.03f,
                            ExperienceReward = 100,
                            GoldReward = 50,
                            Level = 10,
                            MaxHealth = 300,
                            Name = "오크",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Attack = 100,
                            AttackSpeed = 0.6f,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CritDamage = 2f,
                            CritRate = 0.03f,
                            Defense = 50,
                            Evasion = 0.02f,
                            ExperienceReward = 150,
                            GoldReward = 75,
                            Level = 15,
                            MaxHealth = 500,
                            Name = "트롤",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Attack = 200,
                            AttackSpeed = 1.2f,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CritDamage = 2f,
                            CritRate = 0.1f,
                            Defense = 100,
                            Evasion = 0.08f,
                            ExperienceReward = 300,
                            GoldReward = 150,
                            Level = 20,
                            MaxHealth = 1000,
                            Name = "드래곤",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.OfflineRewardType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExperiencePerMinute")
                        .HasColumnType("integer");

                    b.Property<int>("GoldPerMinute")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("OfflineRewardTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ExperiencePerMinute = 2,
                            GoldPerMinute = 1,
                            MaxMinutes = 480,
                            Name = "Basic Offline Reward"
                        });
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentAttack")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("IX_Pets_CharacterId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Pets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pets_CurrentAttack", "\"CurrentAttack\" >= 0");

                            t.HasCheckConstraint("CK_Pets_CurrentMana", "\"CurrentMana\" >= 0");

                            t.HasCheckConstraint("CK_Pets_Level", "\"Level\" >= 1 AND \"Level\" <= 50");
                        });
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttack")
                        .HasColumnType("integer");

                    b.Property<int>("BaseMana")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UK_PetTemplates_Name");

                    b.HasIndex("Rarity")
                        .HasDatabaseName("IX_PetTemplates_Rarity");

                    b.ToTable("PetTemplates", null, t =>
                        {
                            t.HasCheckConstraint("CK_PetTemplates_BaseAttack", "\"BaseAttack\" >= 0");

                            t.HasCheckConstraint("CK_PetTemplates_BaseMana", "\"BaseMana\" >= 0");

                            t.HasCheckConstraint("CK_PetTemplates_Rarity", "\"Rarity\" >= 0 AND \"Rarity\" <= 3");
                        });
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastLoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PlayerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ItemTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("PlayerItems", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PvpMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttackerId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttackerRatingAfter")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerRatingBefore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DefenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("DefenderRatingAfter")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderRatingBefore")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId1")
                        .HasColumnType("integer");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("IX_PvpMatch_SeasonId");

                    b.HasIndex("SeasonId1");

                    b.HasIndex("WinnerId");

                    b.HasIndex("AttackerId", "CreatedAt")
                        .HasDatabaseName("IX_PvpMatch_AttackerId_CreatedAt");

                    b.HasIndex("DefenderId", "CreatedAt")
                        .HasDatabaseName("IX_PvpMatch_DefenderId_CreatedAt");

                    b.ToTable("PvpMatch", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PvpRanking", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRewardClaimed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastMatchAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000);

                    b.Property<int>("SeasonId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("WinStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("SeasonId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SeasonId1");

                    b.HasIndex("SeasonId", "Rating")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_PvpRanking_SeasonId_Rating_DESC");

                    b.ToTable("PvpRanking", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PvpSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PvpSeason_IsActive");

                    b.HasIndex("SeasonNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_PvpSeason_SeasonNumber");

                    b.ToTable("PvpSeason", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("QuestTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TargetCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Status")
                        .HasDatabaseName("IX_Quests_CharacterId_Status");

                    b.HasIndex("CharacterId", "QuestTemplateId", "Status")
                        .HasDatabaseName("IX_Quests_CharacterId_QuestTemplateId_Status");

                    b.ToTable("Quests", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.SkillTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Rarity");

                    b.HasIndex("Type");

                    b.ToTable("SkillTemplates", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.UserDungeonDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DifficultyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DungeonTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("EntryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DungeonTemplateId");

                    b.HasIndex("UserId", "DungeonTemplateId", "DifficultyCode", "Date")
                        .IsUnique();

                    b.ToTable("UserDungeonDailies", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.BattleLog", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Character", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IdleRPG.Domain.ValueObjects.CharacterStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Attack")
                                .HasColumnType("bigint")
                                .HasColumnName("Attack");

                            b1.Property<float>("AttackSpeed")
                                .HasColumnType("real")
                                .HasColumnName("AttackSpeed");

                            b1.Property<float>("CritDamage")
                                .HasColumnType("real")
                                .HasColumnName("CritDamage");

                            b1.Property<float>("CritRate")
                                .HasColumnType("real")
                                .HasColumnName("CritRate");

                            b1.Property<long>("Defense")
                                .HasColumnType("bigint")
                                .HasColumnName("Defense");

                            b1.Property<float>("Evasion")
                                .HasColumnType("real")
                                .HasColumnName("Evasion");

                            b1.Property<long>("MaxHealth")
                                .HasColumnType("bigint")
                                .HasColumnName("MaxHealth");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Player");

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.CharacterBattleProgress", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.CharacterSkill", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.SkillTemplate", "SkillTemplate")
                        .WithMany()
                        .HasForeignKey("SkillTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("SkillTemplate");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.ChatRoom", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.Character", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.ChatRoomParticipant", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.ChatRoom", "Room")
                        .WithMany("Participants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonDifficulty", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdleRPG.Domain.Entities.DungeonTemplate", "Template")
                        .WithMany("Difficulties")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonProgress", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.DungeonDifficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonRunHistory", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.DungeonDifficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonStage", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId");

                    b.HasOne("IdleRPG.Domain.Entities.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LootTable");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonWave", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.DungeonDifficulty", "Difficulty")
                        .WithMany("Waves")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "EquippedCharacter")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdleRPG.Domain.Entities.Character", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquippedCharacter");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.EquippedPets", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.GachaHistory", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.SkillTemplate", "SkillTemplate")
                        .WithMany()
                        .HasForeignKey("SkillTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("SkillTemplate");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.LootItem", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.LootTable", "LootTable")
                        .WithMany("Items")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Pet", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.PetTemplate", "PetTemplate")
                        .WithMany("Pets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("PetTemplate");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PlayerItem", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.ItemTemplate", "ItemTemplate")
                        .WithMany()
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("ItemTemplate");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PvpMatch", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.Character", "Defender")
                        .WithMany()
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.PvpSeason", null)
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.PvpSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.Character", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attacker");

                    b.Navigation("Defender");

                    b.Navigation("Season");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PvpRanking", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.PvpSeason", null)
                        .WithMany("Rankings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.PvpSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Quest", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.UserDungeonDaily", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.DungeonTemplate", "DungeonTemplate")
                        .WithMany()
                        .HasForeignKey("DungeonTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdleRPG.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DungeonTemplate");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Character", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.ChatRoom", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonDifficulty", b =>
                {
                    b.Navigation("Waves");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.DungeonTemplate", b =>
                {
                    b.Navigation("Difficulties");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.LootTable", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PetTemplate", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Player", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.PvpSeason", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Rankings");
                });
#pragma warning restore 612, 618
        }
    }
}
